openapi: 3.0.3
info:
    title: The goakit example downstream service
    description: Archiver is a service that manages the content of HTTP responses
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for archiver
paths:
    /archive:
        post:
            tags:
                - archiver
            summary: archive archiver
            description: Archive HTTP response
            operationId: archiver#archive
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ArchiveRequestBody'
                        example:
                            body: Unde sed nulla.
                            status: 200
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArchiveMedia'
                            example:
                                body: Asperiores quas quas mollitia tempora expedita.
                                href: /archive/1
                                status: 200
    /archive/{id}:
        get:
            tags:
                - archiver
            summary: read archiver
            description: Read HTTP response from archive
            operationId: archiver#read
            parameters:
                - name: id
                  in: path
                  description: ID of archive
                  required: true
                  schema:
                    type: integer
                    description: ID of archive
                    example: 3819557355377074292
                    minimum: 0
                  example: 8570738615275469826
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArchiveMedia'
                            example:
                                body: Provident at explicabo cum odit.
                                href: /archive/1
                                status: 200
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /health:
        get:
            tags:
                - health
            summary: show health
            description: Health check endpoint
            operationId: health#show
            responses:
                "200":
                    description: OK response.
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: Dolorem impedit id facilis fuga vel explicabo.
                            example: Nihil dignissimos laboriosam quaerat quas facilis.
components:
    schemas:
        ArchiveMedia:
            type: object
            properties:
                body:
                    type: string
                    description: HTTP response body content
                    example: Nobis possimus.
                href:
                    type: string
                    description: The archive resouce href
                    example: /archive/1
                    pattern: ^/archive/[0-9]+$
                status:
                    type: integer
                    description: HTTP status
                    example: 200
                    minimum: 0
            example:
                body: Delectus ut esse vitae debitis aut.
                href: /archive/1
                status: 200
            required:
                - href
                - status
                - body
        ArchiveRequestBody:
            type: object
            properties:
                body:
                    type: string
                    description: HTTP response body content
                    example: Et sint.
                status:
                    type: integer
                    description: HTTP status
                    example: 200
                    minimum: 0
            example:
                body: Dolorum corrupti voluptas ut consequuntur.
                status: 200
            required:
                - status
                - body
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
tags:
    - name: archiver
    - name: health
